name = "CryptoSignatures"
uuid = "35cc5888-0c46-470e-89c7-eafcaf79a1aa"
authors = ["Janis Erdmanis <akels14@gmail.com>"]
version = "0.2.2"

[deps]
CryptoGroups = "bc997328-bedd-407e-bcd3-5758e064a52d"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
